In [9]:
import os
import sqlite3
import kagglehub
import pandas as pd

In [2]:
path = kagglehub.dataset_download("tawfikelmetwally/employee-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (0.3.13).
Downloading from https://www.kaggle.com/api/v1/datasets/download/tawfikelmetwally/employee-dataset?dataset_version_number=1...

100%|██████████| 18.5k/18.5k [00:00<00:00, 5.73MB/s]

Extracting files...
Path to dataset files: C:\Users\PC\.cache\kagglehub\datasets\tawfikelmetwally\employee-dataset\versions\1

In [5]:
df = pd.read_csv(path+"/Employee.csv")

In [12]:
df.head(5)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [18]:
df.dropna()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
def fun(text):
    if text == 'Male': 
        return 0
    elif text == 'Female': 
        return 1
    else: 
        return 2
    
df['Gender'] = df.apply(fun)
df.head()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [10]:
ROOT = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
ROOT

'c:\\Users\\PC\\Deskop\\Hand_Landmark_by_Mediapipe'

In [14]:
DATABASE_PATH = os.path.join(ROOT, "database/hands.db")
conn = sqlite3.connect(DATABASE_PATH) 
cursor = conn.cursor()

In [ ]:
cursor.execute('''
                CREATE TABLE test (
                                    Education NVARCHAR(50), 
                                    JoiningYear YEAR, 
                                    City NVARCHAR(50), 
                                    PaymentTier INTERGER, 
                                    AGE INTERGER, 
                                    Gender BOOL,
                                    EverBenched BOOL,
                                    ExperienceInCurrentDomain INTERGER, 
                                    LeaveOrNot BOOL)
                                    ; ''')
conn.commit()

In [13]:
cursor.close()